## Why pipelines??

Pipelines can keep our code neat and clean- from processing & cleaning our data, to creating & fine-tuning models.

It can help prevent Mistakes(like data leakage between train and test set- for example, during cross validation)

In [101]:
import pandas as pd 
import numpy as np

### Load Data

In [102]:
# Load the dataset
ames = pd.read_csv('/home/laaria/Desktop/REPOSITORIES/PRACTICE-NOTEBOOKS/DATA/ames.csv')

ames.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [103]:
ames.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [104]:
ames.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [105]:
ames.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [106]:
ames [[c for c in ames.columns if ames[c].dtype == 'object']].describe()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1460,1460,91,1460,1460,1460,1460,1460,1460,1460,...,1379,1379,1379,1379,1460,7,281,54,1460,1460
unique,5,2,2,4,4,2,5,3,25,9,...,6,3,5,5,3,3,4,4,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,Gd,MnPrv,Shed,WD,Normal
freq,1151,1454,50,925,1311,1459,1052,1382,225,1260,...,870,605,1311,1326,1340,3,157,49,1267,1198

## Pause to Make Observations

# Outline an initial Approach
 
 *take the numeric columns only (ecxluding years)

 *impute missing values with the median using a SimpleImputer

 *scale the data using a StandardScaler
 
 *Model using LinearRegression

In [107]:
# Define which numeric columns ze Dont want to use
# Not including target-related cols, plus the id and year-related cols

not_used_num_cols = ['SalePrice', 'Id', 'YearBuilt','YearRemodAdd ','MoSold', 'YrSold ']

#Define which columns to use

#Grabbing all numeric columns that aren't in the above list
used_cols = [c for c in ames.columns if
             (ames[c].dtype in ['float','int64']) &
             (c not in not_used_num_cols)]

In [108]:
from sklearn.model_selection import train_test_split
# Define our X and Y
X = ames[used_cols]
y = ames['SalePrice']

#Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 13)

In [109]:
from sklearn.impute import SimpleImputer
#instantiate our imputer
imputer = SimpleImputer(strategy = 'median')

#fit our imputer on the training data
imputer.fit(X_train)

#create no-null version of our train and test data
X_train_no_nulls = imputer.transform(X_train)
X_test_no_nulls = imputer.transform(X_test)

In [110]:
from sklearn.preprocessing import  StandardScaler
# Instantiate our scaler
scaler = StandardScaler()

# Fit our Scaler on the no-null training data
scaler.fit(X_train_no_nulls)

# Create processed version of our train and test data
X_train_processed = scaler.transform(X_train_no_nulls)
X_test_processed = scaler.transform(X_test_no_nulls)

In [111]:
X_train_processed.shape

(1095, 34)

## Model the Data--Linear Regression

In [112]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Instantiate our Linear Regression model
linreg = LinearRegression()


#fit our model on our processed training data
linreg.fit(X_train_processed, y_train)

# Grab Predictions out on our train and test sets, to evaluate
train_preds = linreg.predict(X_train_processed)
test_preds = linreg.predict(X_test_processed)

In [113]:
# Print out R2-Score and Root Mean Squared Error for our train and test data
print(f"Train Set R2-Score: {r2_score(y_train, train_preds)}")
print(f"Train Set RMSE: {mean_squared_error(y_train, train_preds, squared= False)}")
print("*"*20)
print(f"Test Set R2-Score: {r2_score(y_test, test_preds)}")
print(f"Test Set RMSE: {mean_squared_error(y_test, test_preds, squared= False)}")

Train Set R2-Score: 0.8724083548153521
Train Set RMSE: 28118.447368054007
********************
Test Set R2-Score: 0.5085901907371855
Test Set RMSE: 57041.30514115523

/home/laaria/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/home/laaria/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

### Pipelines

In [114]:
# Import pipeline
from sklearn.pipeline import Pipeline

In [115]:
# define those steps for our pipeline
Processor = Pipeline (steps=[
    ("imputer", SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [116]:
Processor.fit_transform(X_train)

array([[-0.63325772, -0.46200131, -0.0716991 , ..., -0.06705215,
        -0.10526635, -1.3828836 ],
       [ 0.4320811 , -0.46200131, -0.42485891, ..., -0.06705215,
        -0.10526635, -1.3828836 ],
       [ 0.07696816,  1.14559809, -0.05848765, ..., -0.06705215,
        -0.10526635, -0.62764293],
       ...,
       [-0.1597738 , -0.46200131, -0.46567637, ..., -0.06705215,
        -0.10526635,  1.63807907],
       [ 0.07696816,  1.39678549, -0.04774103, ..., -0.06705215,
        -0.10526635, -0.62764293],
       [-0.86999968,  1.09536061,  0.35806739, ..., -0.06705215,
         1.15468501, -1.3828836 ]])

In [117]:
Processor.fit_transform(X_train).shape

(1095, 34)

In [118]:
#Now add the model-using another pipeline
pipe = Pipeline(steps=[
    ("preprocessor", processor),
    ("linreg", LinearRegression())
    
])

pipe.fit(X_train, y_train)

# Grab predictions out on our train and test sets, to evaluate
train_preds = pipe.predict(X_train)
test_preds = pipe.predict(X_test)

In [119]:
# Print out R2-Score and Root Mean Squared Error for our train and test data
print(f"Train Set R2-Score: {r2_score(y_train, train_preds)}")
print(f"Train Set RMSE: {mean_squared_error(y_train, train_preds, squared= False)}")
print("*"*20)
print(f"Test Set R2-Score: {r2_score(y_test, test_preds)}")
print(f"Test Set RMSE: {mean_squared_error(y_test, test_preds, squared= False)}")

Train Set R2-Score: 0.8724083548153521
Train Set RMSE: 28118.447368054007
********************
Test Set R2-Score: 0.5085901907371855
Test Set RMSE: 57041.30514115523

/home/laaria/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/home/laaria/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

## Cross Validate

In [120]:
## import our cross validation
from sklearn.model_selection import cross_validate

results = cross_validate( pipe, X_train, y_train,
                         cv= 5,
                         return_train_score = True,
                         scoring = ['r2','neg_root_mean_squared_error'])
results

{'fit_time': array([0.1784277 , 0.15707707, 0.07405591, 0.00850892, 0.01316786]),
 'score_time': array([0.00460792, 0.00364542, 0.00345254, 0.00609565, 0.00284958]),
 'test_r2': array([0.85047403, 0.8775205 , 0.84567453, 0.84357204, 0.89189504]),
 'train_r2': array([0.87690112, 0.8702432 , 0.87574298, 0.87850067, 0.8664354 ]),
 'test_neg_root_mean_squared_error': array([-32046.39844691, -25030.21976079, -27845.61775485, -34494.0730484 ,
        -26155.50858803]),
 'train_neg_root_mean_squared_error': array([-27236.96300056, -28966.1249917 , -28381.46872501, -26642.47455568,
        -28691.77802997])}

In [121]:
# lets look at the average, plus a measure of variance, for train and test
print( f"Average Train Set R2-Score: {results['train_r2'].mean()} +/- {results['train_r2'].std()}")
print(f"Average Train Set RMSE:  {results['train_neg_root_mean_squared_error'].mean()*-1 } +/- {results ['train_neg_root_mean_squared_error']}")
print("*"*20)
print( f"Average Test Set R2-Score: {results['test_r2'].mean()} +/- {results['test_r2'].std()}")
print(f"Average Test Set RMSE:  {results['test_neg_root_mean_squared_error'].mean()*-1 } +/- {results ['test_neg_root_mean_squared_error']}")

Average Train Set R2-Score: 0.8735646741890839 +/- 0.004518843487809409
Average Train Set RMSE:  27983.761860583687 +/- [-27236.96300056 -28966.1249917  -28381.46872501 -26642.47455568
 -28691.77802997]
********************
Average Test Set R2-Score: 0.861827226625158 +/- 0.01935669775233017
Average Test Set RMSE:  29114.363519793318 +/- [-32046.39844691 -25030.21976079 -27845.61775485 -34494.0730484
 -26155.50858803]